name: reminderai
description: A smart AI-based reminder app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_local_notifications: ^19.3.0
  speech_to_text: ^6.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  path_provider: ^2.1.3
  chrono_dart: ^2.0.2
  intl: ^0.18.1
  geolocator: ^11.1.0
  geocoding: ^3.0.0
  permission_handler: ^12.0.0
  google_maps_flutter: ^2.6.0
  geofence_service: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
